DAU_FORM_CONFIG = {
    "per_grave": "10",
    "n1": "7",
    "k": "5",
    "year": "2022",
    "month": "9",
    "lmda": "1.5",
    "lmdb": "0.5",
    "lmdc": "0.5",
    "lmdd": "0.1",
    "lmde": "0.5",
    "num_run" : "16",
    "num_group" : "1",
    "num_output_solution" : "5",
    "gs_level" : "5",
    "gs_cutoff" : "8000",
    "index_of_solution" : "0",
    "time_limit_sec": "120",
    "penalty_coef": "10000",
}

SA_FORM_CONFIG = {
    "per_grave": "10",
    "n1": "7",
    "k": "5",
    "num_sweeps": "150000",
    "year": "2022",
    "month": "9",
    "lmda": "1.5",
    "lmdb": "0.5",
    "lmdc": "0.5",
    "lmdd": "0.1",
    "lmde": "0.5",
    "index_of_solution" : "0",
    "number_of_runs" : "10"
}
